

#  condition to run the automation tasks (when )
on: 
  push: 
    branches: ["master"]
env: 
  IMAGE_NAME: reactjs-fullstack-special
jobs: 
  ci-job: 
    runs-on: ubuntu-latest
    environment: DEMO_ENV
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3
      - name: Using Commit SHA 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV  
      - name: Login to Dockerhub 
        run: |
          echo "${{secrets.PASSWORD}}" | docker login -u ${{secrets.USERNAME}} --password-stdin
      - name: Build Image and Tag 
        run: |
          docker build -t ${{secrets.USERNAME}}/${{env.IMAGE_NAME}}:${{env.TAG}} .

      - name: Install Trivy 
        if: false 
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy command in order to scan and save report 
        if: false 
        id: trivy
        run: |
          trivy image \
            --format json \
            --output trivy-report.json \
            --severity CRITICAL,HIGH \
            ${{secrets.USERNAME}}/${{env.IMAGE_NAME}}:${{env.TAG}} || true
      - name: Parse vulnerabilities and Build Summary
        if: false
        run: |
          # Count vulnerabilities
          CRITICAL_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-report.json || echo 0)
          HIGH_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy-report.json || echo 0)
          
          # Extract top 5 Critical Vulnerabilities for the report
          DETAIL_LIST=$(jq -r '.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL") | "• \(.VulnerabilityID) (\(.PkgName))" ' trivy-report.json | head -n 10)
          
          # Save to Environment
          echo "CRITICAL=$CRITICAL_COUNT" >> $GITHUB_ENV
          echo "HIGH=$HIGH_COUNT" >> $GITHUB_ENV
          
          # Use a multiline environment variable for the details
          {
            echo "VULN_DETAILS<<EOF"
            echo "$DETAIL_LIST"
            echo "EOF"
          } >> $GITHUB_ENV  

      - name: Send Telegram Report       
        if: false 
        #if: env.CRITICAL != '0' || env.HIGH != '0'
        run: |
          # Build the multiline message
          MESSAGE="🚨 *Docker Scan Results*
          
          *Image:* \`${{ env.IMAGE_NAME }}:${{ env.TAG }}\`
          *Critical:* ${{ env.CRITICAL }}
          *High:* ${{ env.HIGH }}
          
          *Top Critical Issues:*
          ${{ env.VULN_DETAILS }}
          
          _Check GitHub Action logs for full report._"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode="Markdown" \
            -d text="$MESSAGE"
      - name: Fail if vulnerabilities found 
       # if: env.CRITICAL != '0' || env.HIGH != '0'
        if: false
        run: exit 1     
      - name: Push to Dockerhub 
        #if: success()
        run: |
          docker push ${{secrets.USERNAME}}/${{env.IMAGE_NAME}}:${{env.TAG}}
      - name: Logout from Dockerhub 
        if: always()
        run: |
          docker logout 
  cd-job: 
    needs: ci-job
    runs-on: ubuntu-latest
    environment: GCP_ENV
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3
        # tag is the version of our image 
      - name: Use with SHA 
        run: | 
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Deploy via SSH to GCP VM 
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          envs: TAG
          script: |
            echo "Current location is $(pwd) "
       
            echo "remove the container "
            docker stop reactjs-app || true 
            docker rm reactjs-app || true 

            echo "Pulling the updating image "
            docker pull "lyvanna544/${{env.IMAGE_NAME }}:${{ env.TAG }}"

            echo "Running new containers "
            docker run -d \
              --name reactjs-app \
              -p 3001:80 \
              "lyvanna544/${{env.IMAGE_NAME }}:${{ env.TAG }}"
            
  
